// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA76s979_icZf0n1GnEtoNbIgkTwoGjDrE',
    appId: '1:22611911509:web:f3bc1062ce9163cb6845dc',
    messagingSenderId: '22611911509',
    projectId: 'todo-b37c1',
    authDomain: 'todo-b37c1.firebaseapp.com',
    storageBucket: 'todo-b37c1.appspot.com',
    measurementId: 'G-JLVPFJ0GGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlmohPvwXaDl9QbWM6eA-r47ZQK4CjmAY',
    appId: '1:22611911509:android:9a6934caeb97077d6845dc',
    messagingSenderId: '22611911509',
    projectId: 'todo-b37c1',
    storageBucket: 'todo-b37c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpUG1r3b0-hT_qTjPQPxt1ZbUcl8wdsuA',
    appId: '1:22611911509:ios:8d8fb9fdba0039326845dc',
    messagingSenderId: '22611911509',
    projectId: 'todo-b37c1',
    storageBucket: 'todo-b37c1.appspot.com',
    iosBundleId: 'dev.bogibek.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpUG1r3b0-hT_qTjPQPxt1ZbUcl8wdsuA',
    appId: '1:22611911509:ios:4fc2cd0cd33b058c6845dc',
    messagingSenderId: '22611911509',
    projectId: 'todo-b37c1',
    storageBucket: 'todo-b37c1.appspot.com',
    iosBundleId: 'dev.bogibek.todo.RunnerTests',
  );
}
